import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#adc7f8",
        primary: "#001029",
        "secondary-fixed-dim": "#ffb4a3",
        "on-surface": "#1a1b1f",
        "on-primary-fixed-variant": "#2c4771",
        "tertiary-container": "#1b2828",
        "on-error": "#ffffff",
        "outline-variant": "#c4c6d0",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#bbc9c9",
        surface: "#faf9fd",
        "on-tertiary-fixed-variant": "#3c4949",
        "on-primary-fixed": "#001b3d",
        "on-secondary-fixed-variant": "#8b1a00",
        "surface-dim": "#dad9dd",
        tertiary: "#071313",
        "on-surface-variant": "#43474e",
        "secondary-container": "#de3002",
        background: "#faf9fd",
        "error-container": "#ffdad6",
        "inverse-surface": "#2f3033",
        "on-background": "#1a1b1f",
        "on-primary": "#ffffff",
        "surface-container-low": "#f4f3f7",
        "surface-container-high": "#e9e7ec",
        "surface-container": "#eeedf1",
        "on-tertiary-container": "#828f90",
        "on-secondary-container": "#fffbff",
        "on-tertiary": "#ffffff",
        "primary-container": "#03254d",
        "inverse-on-surface": "#f1f0f4",
        "on-tertiary-fixed": "#111e1e",
        "surface-variant": "#e3e2e6",
        error: "#ba1a1a",
        secondary: "#b22400",
        "on-primary-container": "#738dbb",
        "on-secondary-fixed": "#3d0600",
        "surface-tint": "#455f8a",
        outline: "#74777f",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#adc7f8",
        "surface-bright": "#faf9fd",
        "secondary-fixed": "#ffdad2",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "tertiary-fixed": "#d7e5e5",
        "surface-container-highest": "#e3e2e6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        gutter: "24px",
        sm: "8px",
        md: "16px",
        unit: "4px",
        xs: "4px",
        xl: "40px",
        margin: "32px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
